version: "3.8"

services:
  # PostgreSQL Service
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recommendations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # PySpark Service
  pyspark:
    build:
      context: ./batch_processing
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - kafka

  # Streamlit Service
  streamlit:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - pyspark

volumes:
  postgres_data:
